// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type AnalyzeInput struct {
	Prompt string               `json:"prompt"`
	Config *OptimizeConfigInput `json:"config"`
}

type AnalyzeResult struct {
	Status    AnalyzeStatus `json:"status"`
	Questions []*Question   `json:"questions,omitempty"`
	Prompt    *string       `json:"prompt,omitempty"`
	Findings  []*Finding    `json:"findings,omitempty"`
}

type AppliedRule struct {
	ID          string  `json:"id"`
	SourceURL   string  `json:"sourceUrl"`
	TokensDelta *int    `json:"tokensDelta,omitempty"`
	Method      *string `json:"method,omitempty"`
	Model       *string `json:"model,omitempty"`
}

type EstimateResult struct {
	Tokens int `json:"tokens"`
}

type Finding struct {
	ID          string        `json:"id"`
	Category    string        `json:"category"`
	Severity    int           `json:"severity"`
	SectionID   *string       `json:"sectionId,omitempty"`
	SectionType *string       `json:"sectionType,omitempty"`
	RuleID      *string       `json:"ruleId,omitempty"`
	Summary     string        `json:"summary"`
	Source      FindingSource `json:"source"`
}

type Health struct {
	Status string `json:"status"`
}

type InvestigateInput struct {
	WorkspacePath string        `json:"workspacePath"`
	TargetProfile TargetProfile `json:"targetProfile"`
}

type InvestigationFile struct {
	Path           string `json:"path"`
	SectionType    string `json:"sectionType"`
	ContentPreview string `json:"contentPreview"`
}

type InvestigationResult struct {
	Files             []*InvestigationFile `json:"files"`
	SuggestedCommands []string             `json:"suggestedCommands"`
}

type MdcSuggestion struct {
	Filename string `json:"filename"`
	Content  string `json:"content"`
}

type Mutation struct {
}

type OptimizeArtifacts struct {
	CursorMdcSuggestions []*MdcSuggestion `json:"cursorMdcSuggestions,omitempty"`
}

type OptimizeConfigInput struct {
	TargetProfile TargetProfile `json:"targetProfile"`
	MaxTokens     int           `json:"maxTokens"`
	Tokenizer     string        `json:"tokenizer"`
	DeepDive      *bool         `json:"deepDive,omitempty"`
	WorkspacePath *string       `json:"workspacePath,omitempty"`
}

type OptimizeInput struct {
	Prompt  string               `json:"prompt"`
	Config  *OptimizeConfigInput `json:"config"`
	Answers map[string]string    `json:"answers,omitempty"`
}

type OptimizeReport struct {
	InputTokens       int            `json:"inputTokens"`
	OutputTokens      int            `json:"outputTokens"`
	ReductionPercent  float64        `json:"reductionPercent"`
	TargetProfile     string         `json:"targetProfile"`
	AppliedRules      []*AppliedRule `json:"appliedRules"`
	TruncatedSections []string       `json:"truncatedSections"`
}

type OptimizeResult struct {
	OptimizedPrompt string             `json:"optimizedPrompt"`
	Artifacts       *OptimizeArtifacts `json:"artifacts"`
	Report          *OptimizeReport    `json:"report"`
}

type Query struct {
}

type Question struct {
	ID     string  `json:"id"`
	Text   string  `json:"text"`
	RuleID *string `json:"ruleId,omitempty"`
}

type AnalyzeStatus string

const (
	AnalyzeStatusNeedsInput AnalyzeStatus = "NEEDS_INPUT"
	AnalyzeStatusReady      AnalyzeStatus = "READY"
)

var AllAnalyzeStatus = []AnalyzeStatus{
	AnalyzeStatusNeedsInput,
	AnalyzeStatusReady,
}

func (e AnalyzeStatus) IsValid() bool {
	switch e {
	case AnalyzeStatusNeedsInput, AnalyzeStatusReady:
		return true
	}
	return false
}

func (e AnalyzeStatus) String() string {
	return string(e)
}

func (e *AnalyzeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnalyzeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnalyzeStatus", str)
	}
	return nil
}

func (e AnalyzeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AnalyzeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AnalyzeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FindingSource string

const (
	FindingSourceHeuristic FindingSource = "HEURISTIC"
	FindingSourceLlm       FindingSource = "LLM"
)

var AllFindingSource = []FindingSource{
	FindingSourceHeuristic,
	FindingSourceLlm,
}

func (e FindingSource) IsValid() bool {
	switch e {
	case FindingSourceHeuristic, FindingSourceLlm:
		return true
	}
	return false
}

func (e FindingSource) String() string {
	return string(e)
}

func (e *FindingSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FindingSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FindingSource", str)
	}
	return nil
}

func (e FindingSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FindingSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FindingSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type TargetProfile string

const (
	TargetProfileClaude TargetProfile = "CLAUDE"
	TargetProfileCodex  TargetProfile = "CODEX"
	TargetProfileOpenai TargetProfile = "OPENAI"
	TargetProfileDevin  TargetProfile = "DEVIN"
	TargetProfileCursor TargetProfile = "CURSOR"
)

var AllTargetProfile = []TargetProfile{
	TargetProfileClaude,
	TargetProfileCodex,
	TargetProfileOpenai,
	TargetProfileDevin,
	TargetProfileCursor,
}

func (e TargetProfile) IsValid() bool {
	switch e {
	case TargetProfileClaude, TargetProfileCodex, TargetProfileOpenai, TargetProfileDevin, TargetProfileCursor:
		return true
	}
	return false
}

func (e TargetProfile) String() string {
	return string(e)
}

func (e *TargetProfile) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TargetProfile(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TargetProfile", str)
	}
	return nil
}

func (e TargetProfile) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *TargetProfile) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e TargetProfile) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
